name: Build and Release JAR

on:
  release:
    types: [created]
    
permissions:
  contents: write
  packages: write
  
jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests -f pom.xml

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/gitlet-1.0-SNAPSHOT.jar
          asset_name: gitlet-1.0-SNAPSHOT.jar 
          asset_content_type: application/java-archive
